"""Separar Producto y ProductoPrecio

Revision ID: 28a5d5f92462
Revises: 40e0472d5cd5
Create Date: 2025-02-17 20:17:36.291577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28a5d5f92462'
down_revision: Union[str, None] = '40e0472d5cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto_precios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('precio_costo', sa.Float(), nullable=False),
    sa.Column('ganancia', sa.Float(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('productos', sa.Column('codigo_de_barra', sa.String(), nullable=False))
    op.add_column('productos', sa.Column('fecha_caducidad', sa.DateTime(), nullable=False))
    op.add_column('productos', sa.Column('vencido', sa.Boolean(), nullable=False))
    op.drop_column('productos', 'Precio')
    op.drop_column('productos', 'Codigo_de_barra')
    op.drop_column('productos', 'Vencido')
    op.drop_column('productos', 'Fecha_de_caducidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('Fecha_de_caducidad', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('Vencido', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('Codigo_de_barra', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('Precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('productos', 'vencido')
    op.drop_column('productos', 'fecha_caducidad')
    op.drop_column('productos', 'codigo_de_barra')
    op.drop_table('producto_precios')
    # ### end Alembic commands ###
