"""Separar Producto y ProductoPrecio

Revision ID: 40e0472d5cd5
Revises: ba5c77387803
Create Date: 2025-02-17 20:15:30.464751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e0472d5cd5'
down_revision: Union[str, None] = 'ba5c77387803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
