"""Separar Producto y ProductoPrecio

Revision ID: 49ed7ded2136
Revises: 28a5d5f92462
Create Date: 2025-02-18 22:58:04.706665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ed7ded2136'
down_revision: Union[str, None] = '28a5d5f92462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
